### Never send your "passwords" in Production ###

x-base: &common
  env_file: .env
  build:
    dockerfile: Dockerfile
  restart: always
  networks:
    - lipebol-network
  deploy:
    resources:
      limits:
        cpus: 2
        memory: 2048M
        pids: 200
  memswap_limit: 4096M
  logging:
    options:
      max-size: 10M
      max-file: 3
  security_opt:
    - no-new-privileges=true
  environment:
    - PUID=1000
    - PGID=1000

services:
  spark:
    <<: *common
    build:
      context: ./spark
    tty: true
    stdin_open: true
    image: lipebol/spark:v1
    container_name: apache-spark
    ports:
      - 7077:7077 # master
      - 8081:8080 # master-ui
      - 4040:4040 # driver-ui
      - 7777:7777 # event-logging
      - 6066:6066 # rest
    volumes:
      - ./spark:/srv/spark
    working_dir: /srv/spark

  drill:
    <<: *common
    build:
      context: ./drill
    tty: true
    stdin_open: true
    image: lipebol/drill:v1
    container_name: apache-drill
    ports:
      - 8047:8047 # web/rest
      - 31010:31010 # jdbc
    volumes:
      - ./drill/conf/drill-override.conf:/opt/drill/conf/drill-override.conf
      - ./drill/conf/storage-plugins-override.conf:/opt/drill/conf/storage-plugins-override.conf
      - ./drill/files:/.data/files
      - ./drill/tables:/.data/tables
    working_dir: /opt/drill

  minio:
    <<: *common
    command: server /mnt/data --console-address :9090
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: lipebol
      MINIO_CONFIG_ENV_FILE: /etc/config.env
    expose:
     - 9000 # main
    ports:
      - 9090:9090 # admin
    volumes:
      - ./minio/data:/mnt/data
      - ./minio/.env:/etc/config.env
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  lipebol-network:
    external: true
    name: lipebol-network