### Never send your "passwords" in Production ###

services:
  spark:
    env_file: .env
    build:
      context: ./spark
      dockerfile: ${DEFAULT_BUILD}
    tty: true
    stdin_open: true
    image: spark/v1
    container_name: spark
    restart: ${DEFAULT_RESTART_MODE}
    ports:
      - 7077:7077 # master
      - 8081:8080 # master-ui
      - 4040:4040 # driver-ui
      - 7777:7777 # event-logging
      - 6066:6066 # rest
    volumes:
      - ./spark:/srv/spark
    working_dir: /srv/spark
    networks:
     - ${DEFAULT_NETWORK}
    deploy:
      resources:
        limits:
          cpus: ${DEFAULT_CORE}
          memory: ${DEFAULT_MEM}
    memswap_limit: ${DEFAULT_MEM_SWAP}

  drill:
    env_file: .env
    build:
      context: ./drill
      dockerfile: ${DEFAULT_BUILD}
    tty: true
    stdin_open: true
    image: drill/v1
    container_name: drillEx
    restart: ${DEFAULT_RESTART_MODE}
    ports:
      - 8047:8047 # web/rest
      - 31010:31010 # jdbc
    volumes:
      - ./drill/conf/drill-override.conf:/opt/drill/conf/drill-override.conf
      - ./drill/conf/storage-plugins-override.conf:/opt/drill/conf/storage-plugins-override.conf
      - ./drill/files:/.data/files
      - ./drill/tables:/.data/tables
    working_dir: /opt/drill
    networks:
     - ${DEFAULT_NETWORK}
    deploy:
      resources:
        limits:
          cpus: ${DEFAULT_CORE}
          memory: ${DEFAULT_MEM}
    memswap_limit: ${DEFAULT_MEM_SWAP}

  minio:
    env_file: .env
    command: server /mnt/data --console-address :9090
    image: quay.io/minio/minio:latest
    container_name: minEx
    restart: ${DEFAULT_RESTART_MODE}
    environment:
      MINIO_ROOT_USER: ${DEFAULT_USER}
      MINIO_CONFIG_ENV_FILE: /etc/config.env
    #expose:
    #  - ${MINEX_PORT}
    ports:
      - 9000:9000 # main
      - 9090:9090 # admin
    volumes:
      - ./minio/data:/mnt/data
      - ./minio/.env:/etc/config.env
    networks:
     - ${DEFAULT_NETWORK}
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live
      interval: ${DEFAULT_INTERVAL}
      timeout: ${DEFAULT_TIMEOUT}
      retries: ${DEFAULT_RETRIES}
    deploy:
      resources:
        limits:
          cpus: ${DEFAULT_CORE}
          memory: ${DEFAULT_MEM}
    memswap_limit: ${DEFAULT_MEM_SWAP}

networks:
  data-acervus-network:
    external: true
    name: ${DEFAULT_NETWORK}